### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by pdias** [widop/WidopGoogleAnalyticsBundle#16]
Hello,

As you say the doc's, i create a [Google App](http://code.google.com/apis/console) and enabled the Google Analytics service... For exemple this site: www.psaid.pt

With this bundle can i access (from my PC / localhost) to the Google Analytics ??

Excuse this newbie question...

Thanks,

Paulo

**Comment by egeloen** [comment]
@pdias Yes, the bunde uses [OAuth2 for server to server applications](https://developers.google.com/accounts/docs/OAuth2ServiceAccount) (No need of user interaction). So, your localhost or any other "server" can have a direct access to the Google Analytics service.

**Comment by egeloen** [comment]
To complete my answer, the bundle only provides a read only access for querying purpose.

**Comment by pdias** [comment]
Thanks
