### ISSUE TITLE
Wrong tip in usage documentation

### ISSUE THREAD

**Issue by fertandil87** [widop/WidopGoogleAnalyticsBundle#19]
Hi, I think that this is wrong:

Get the mail which will gives you the client_id and profile_id or simply copy them from Google App (use "Email Adress" as client_id <b>and "Client ID" as your profile_id).</b>

bolder is wrong for me, if I try to do that I will get a regular expresion error from the bundle.

**Comment by egeloen** [comment]
@fertandil87 Thx for reporting it. You're right, there is an issue in the documentation but I don't remember where I get this value the last time I have used the bundle... @tmartin An idea?

**Comment by tmartin** [comment]
Yep, the `profile_id` is actually located in your Google Analytics admin panel in `Account List > Your Account > Your Property > Your Profile > Profile Settings`. It's a bit tricky. Will fix this, thanks.

**Comment by egeloen** [comment]
@tmartin You will fix the issue or should I fix it?

**Comment by egeloen** [comment]
ping @tmartin
