### ISSUE TITLE
Check for html response

### ISSUE THREAD

**Issue by maxkorolev** [widop/WidopGoogleAnalyticsBundle#24]
https://github.com/widop/WidopGoogleAnalyticsBundle/blob/master/Model/GoogleAnalyticsService.php#L71

Sometimes GA can return html response, and in $content variable wil be that:

```
<!DOCTYPE html>
<html lang=en>
  <meta charset=utf-8>
  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
  <title>Error 413 (Request Entity Too Large)!!1</title>
...
```

it's not json, it's html.

This can happen when in request field Filters is too big (more than 50 items)
Check this please.

**Comment by egeloen** [comment]
@KorolevMaksimA Thx for reporting it! The issue should be fixed now.
