### ISSUE TITLE
Split bundle into multiple modules to allow reuse outside of Symfony Bundle ecosystem

### ISSUE THREAD

**Issue by gunnarlium** [widop/WidopGoogleAnalyticsBundle#28]
As discussed on email, I would like to be able to reuse the Google Analytics part of this repo, without depending on the framework bundle (and it's dependencies).

Suggested modules:
- `WidopHttpAdapter` - for interface and adapters
- `WidopHttpAdpaterBundle` - for integration of WidowHttpAdapter in Symfony fullstack
- `WidopGoogleAnalytics` - for current model classes
- `WidopGoogleAnalyticsBundle` -  for Symfony integration

It would then also make sense to provide a `GoogleAnalyticsServiceProvider` for integration with Silex.

**Comment by egeloen** [comment]
All is done! You can now use [`widop/google-analytics`](https://github.com/widop/google-analytics) or [`widop/http-adapter`](https://github.com/widop/http-adapter) as dedicated components. Enjoy!

**Comment by gunnarlium** [comment]
Perfect! Works great!

**Comment by tmartin** [comment]
:+1: @egeloen
