### ISSUE TITLE
invalid_request

### ISSUE THREAD

**Issue by dariuszp** [widop/WidopGoogleAnalyticsBundle#30]
After updating bundle to latest I constantly receive invalid_request error when bundle is trying to get access token.

vendor/widop/google-analytics-bundle/Widop/GoogleAnalyticsBundle/Model/Client.php

line 180. Response is something like { error: invalid_request }. Version that I had for past few weeks (1.0-dev if I remember) worked fine. I restored bundle code from backup and everything work like a charm again.

```
public function getAccessToken()
    {
        if ($this->accessToken === null) {
            $headers = array('Content-Type' => 'application/x-www-form-urlencoded');
            $content = array(
                'grant_type'     => 'assertion',
                'assertion_type' => 'http://oauth.net/grant_type/jwt/1.0/bearer',
                'assertion'      => $this->generateJsonWebToken(),
            );

            $response = json_decode($this->httpAdapter->postContent($this->url, $headers, $content));

            if (isset($response->error)) {
                throw new \Exception(sprintf('Failed to retrieve access token (%s).', $response->error));
            }

            $this->accessToken = $response->access_token;
        }


        return $this->accessToken;
    }
```

After returning to previous version

**Comment by egeloen** [comment]
Can you copy/paste the request sent to google? (obviously without your credentials :))

**Comment by dariuszp** [comment]
URL: https://accounts.google.com/o/oauth2/token
HEADERS: [  'Content-Type' => string 'application/x-www-form-urlencoded' ]
CONTENT:
[
    [grant_type] => assertion 
    [assertion_type] => http://oauth.net/grant_type/jwt/1.0/bearer 
    [assertion] => eyJhb... str(530)
]

---

JsonWebToken:
string '{"iss":"here_is_my_client_id_from_config.yml","scope":"https:\/\/www.googleapis.com\/auth\/analytics.readonly","aud":"https:\/\/accounts.google.com\/o\/oauth2\/token","exp":1379950013,"iat":1379946413}' (length=240)

Any changes in configuration what I could miss ?

**Comment by egeloen** [comment]
No, there is no BC breaks in how it works, just in how it is structured. So, it should still work but an `invalid_request` really means there is something wrong in the request generation... I will try this new version in a project which uses the old one & will come back.

**Comment by egeloen** [comment]
Btw, what is the http adapter you use? cUrl?

**Comment by egeloen** [comment]
@dariuszp I have reproduced the issue, will check what the problem.

**Comment by ajcerqueti** [comment]
Just wanted to add that I did an update to my dev environment today to 1.1.0, and am getting same issue. Production is using 1.0.1 without issue, but rolling back the WGAB all the way back on dev didn't fix anything, leading me to believe it's actually an issue with the WidopHttpAdapterBundle instead. Would recommend changing your composer.json to:
        "widop/google-analytics-bundle": "1.0.1",
        "widop/http-adapter-bundle": "1.0.1",
until this is resolved.

**Comment by egeloen** [comment]
The bug has been introduced in https://github.com/widop/WidopHttpAdapterBundle/commit/c47befdd32011c2a9a148d800e754b62d7e1c602 I'm currently working on a patch. Anyway, it is only related to curl & stream, so if you change the http adapter to guzzle, you should get rid of this error.

**Comment by egeloen** [comment]
I just release a new version of the `widop/http-adapter` which is patched. You can update to the 1.1.0 & all should work again!

**Comment by dariuszp** [comment]
I will try in 1-2 hours. I was using cURL adapter. Thanks.
