### ISSUE TITLE
Private key only json file

### ISSUE THREAD

**Issue by lughino** [widop/WidopGoogleAnalyticsBundle#7]
I created the key, but makes me download format only json from google ..
I can not find anywhere the certificate. P12.
Can you tell me if I put the key in json format?
thanks

**Comment by egeloen** [comment]
@Lughino When you create your service account, at the end of the process, a popup allows you to download the generated key (the P12 file). After this moment, you can only download a JSON file which is not needed for the bundle...

Your only solution is to delete your key on the google console & it will generate a new certificate for you.
